///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ZoomDetailsData {
/*
{
  "zoomId": 1,
  "regsiter_date": "2023-05-16T13:37:56.871Z",
  "zoomMeetId": "kesa789t3gu",
  "zoomMeetTopic": "Medations",
  "zoomMeetPassword": "kesava",
  "zoommeetdateandtime": "16,April,Monday",
  "zoommeetupcomingdate": null,
  "zoom_Available_Slots": 40,
  "zoom_Total_Slots": 40,
  "zoommeetURL": "kesava"
} 
*/

  int? zoomId;
  String? regsiterDate;
  String? zoomMeetId;
  String? zoomMeetTopic;
  String? zoomMeetPassword;
  String? zoommeetdateandtime;
  String? zoommeetupcomingdate;
  int? zoomAvailableSlots;
  int? zoomTotalSlots;
  String? zoommeetURL;

  ZoomDetailsData({
    this.zoomId,
    this.regsiterDate,
    this.zoomMeetId,
    this.zoomMeetTopic,
    this.zoomMeetPassword,
    this.zoommeetdateandtime,
    this.zoommeetupcomingdate,
    this.zoomAvailableSlots,
    this.zoomTotalSlots,
    this.zoommeetURL,
  });
  ZoomDetailsData.fromJson(Map<String, dynamic> json) {
    zoomId = json['zoomId']?.toInt();
    regsiterDate = json['regsiter_date']?.toString();
    zoomMeetId = json['zoomMeetId']?.toString();
    zoomMeetTopic = json['zoomMeetTopic']?.toString();
    zoomMeetPassword = json['zoomMeetPassword']?.toString();
    zoommeetdateandtime = json['zoommeetdateandtime']?.toString();
    zoommeetupcomingdate = json['zoommeetupcomingdate']?.toString();
    zoomAvailableSlots = json['zoom_Available_Slots']?.toInt();
    zoomTotalSlots = json['zoom_Total_Slots']?.toInt();
    zoommeetURL = json['zoommeetURL']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['zoomId'] = zoomId;
    data['regsiter_date'] = regsiterDate;
    data['zoomMeetId'] = zoomMeetId;
    data['zoomMeetTopic'] = zoomMeetTopic;
    data['zoomMeetPassword'] = zoomMeetPassword;
    data['zoommeetdateandtime'] = zoommeetdateandtime;
    data['zoommeetupcomingdate'] = zoommeetupcomingdate;
    data['zoom_Available_Slots'] = zoomAvailableSlots;
    data['zoom_Total_Slots'] = zoomTotalSlots;
    data['zoommeetURL'] = zoommeetURL;
    return data;
  }
}

class ZoomDetails {
/*
{
  "data": {
    "zoomId": 1,
    "regsiter_date": "2023-05-16T13:37:56.871Z",
    "zoomMeetId": "kesa789t3gu",
    "zoomMeetTopic": "Medations",
    "zoomMeetPassword": "kesava",
    "zoommeetdateandtime": "16,April,Monday",
    "zoommeetupcomingdate": null,
    "zoom_Available_Slots": 40,
    "zoom_Total_Slots": 40,
    "zoommeetURL": "kesava"
  },
  "code": 201,
  "received": true
} 
*/

  ZoomDetailsData? data;
  int? code;
  bool? received;

  ZoomDetails({
    this.data,
    this.code,
    this.received,
  });
  ZoomDetails.fromJson(Map<String, dynamic> json) {
    data =
        (json['data'] != null) ? ZoomDetailsData.fromJson(json['data']) : null;
    code = json['code']?.toInt();
    received = json['received'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    data['code'] = code;
    data['received'] = received;
    return data;
  }
}
